repo_name: lifnaja/python-tutorial
site_name: Python tutorial
site_url: https://lifnaja.github.io/python-tutorial/
repo_url: https://github.com/lifnaja/python-tutorial


theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


nav:
  - Home: index.md
  - Python:
    - Python Basic:
      - Introduction to Python: python/python-basic/basic_python.md
      - Basic Operators: python/python-basic/basic_operators.md
      - Strings & String Manipulation: python/python-basic/strings.md
      - Input Function: python/python-basic/input_function.md
      - Comment: python/python-basic/comments.md
      - Conditionals (if-else): python/python-basic/conditionals.md
      - Loops (for, while): python/python-basic/loops.md
      - Functions: python/python-basic/function.md
      - Importing Modules: python/python-basic/importing_modules.md
      - List: python/python-basic/lists.md
      - Tuples: python/python-basic/tuples.md
      - Dictionaries: python/python-basic/dictionaries.md

    - Object-Oriented Programming:
      - Classes and Objects: python/oop/classes_and_objects.md

    - More Python Features:
      - Exception Handling: python/more-features/exception_handling.md
      - Context Manager: python/more-features/context_manager.md
      - Unit Test: python/more-features/unit_test.md
      - Environment Variable: python/more-features/environment_variables.md
      - Virtual Environment: python/more-features/virtual_environment.md
      - Dependencies Management: python/more-features/dependencies_management.md


  # - Pandas:
  #   - Intro: pandas/intro_pandas.md
  #   - Read and Write Data: pandas/read_and_write_tabular_data.md
  #   - Select subset data: pandas/select_subset_data.md
  #   - Plot int Pandas: pandas/plots_in_pandas.md