repo_name: lifnaja/python-tutorial
site_name: Python tutorial
site_url: https://lifnaja.github.io/python-tutorial/
repo_url: https://github.com/lifnaja/python-tutorial


theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details


nav:
  - Home: index.md
  - Python Basics:
    - Introduction to Python: python/1_basic_python.md
    - Basic Operators: python/2_basic_operators.md
    - Strings & String Manipulation: python/3_strings.md
    - Conditionals (if-else): python/4_conditionals.md


    - Loops (for, while): python/4_loops.md
    - Functions: python/5_functions.md
    - Importing Modules: python/6_importing_modules.md
    - List and Tuples: python/lists_tuples.md
    - Dictionaries: python/dictionaries.md
    - Function: python/function.md
  - Data Structures:
    - Classes and Objects: python/classes_and_objects.md
    - Condition: python/condition.md
    - Loops: python/loops.md
    - Exception Handling: python/exception_handling.md
    - Context Manager: python/context_manager.md
  - Object-Oriented Programming:
    - Importing Modules: python/importing_modules.md
    - Unit Test: python/unit_test.md
  - More Python Features:
    - Virtual Environment: python/virtual_environment.md
  - Pandas:
    - Intro: pandas/intro_pandas.md
    - Read and Write Data: pandas/read_and_write_tabular_data.md
    - Select subset data: pandas/select_subset_data.md
    - Plot int Pandas: pandas/plots_in_pandas.md